### ISSUE TITLE
Are the table content/values used while training?

### ISSUE THREAD

**Issue by shabbie** [ElementAI/picard#28] opened 2021-11-25 16:54 UTC
There are two queries regading the training process and the inference which are described below:
1. Inside the config file, the following flag "schema_serialization_with_db_content" is set to be true, however it is not clear by looking at the code whether the table data values are used during the training and evaluation.

2. In the predictions_eval.json file that gets generated at inference has the  key "Context" present for each template which has the following structure : Question | db_id | table columns. Now, when the tag is observed, the column names are modified having an additional info. appended from the question content. An example is provided below:
`"context": "What is the difference between the Number of passengers carried in Bolivia in 1998 and that in 1999? | 1_8655 | table_data : years, series **( bolivia )**, number_of_passengers_carried_by_air_carriers_registered_in_a_country_number_of_passengers_carried"`
The additional content is mentioned between double asterik. Is this context fed to model and if not, what does it represent?

kindly clarify the above queries.

**Comment by tscholak** [comment] 2021-11-26 00:29
Hi @shabble!

1. When `schema_serialization_with_db_content` is `True`, then relevant database content is appended to column names in the context.
2. The context is the input to the model. Therefore, `bolivia` will be part of it.

**Comment by tscholak** [comment] 2021-12-01 19:11
Hi, I cannot comment on the changes you are proposing, I'm not sure what you are trying to do. The code you are modifying is part of the test suite evaluation framework by Ruiqi Zhong et al., and it is a third-party dependency to this project that we mostly left unmodified. Therefore, questions about its function and how to adapt it are best directed upstream.

The reason for why your changes do not affect program behaviour is that the images are created in a fully reproducible way from git commits pushed to the main branch of this repository. If you make changes locally and you feel like that people will benefit from your changes (e.g. bug fixes or feature additions), you are invited to open a PR and ask me to merge these changes to main. In other cases, it is best to either change the way images are built or to mount your local working directory in the docker container in the /app/seq2seq folder.

**Comment by shabbie** [comment] 2021-12-10 12:39
Thanks for the reply. I got it resolved by changing the image, but could not get PICARD working with it

**Comment by tscholak** [comment] 2021-12-10 13:10
How can I help with that? How did you change the image?

**Comment by tscholak** [comment] 2022-02-24 18:22
closing due to inactivity. please let me know if you need further help by reopening the issue.

**Closed by tscholak** 2022-02-24 18:22 UTC
Labels: question
