### ISSUE TITLE
Issue with loading dataset

### ISSUE THREAD

**Issue by PramuPerera** [ElementAI/picard#61] opened 2022-02-19 14:51 UTC
After cloning the package, when I run `make train` I get an error. Following is the trace:

Downloading and preparing dataset spider/spider to /transformers_cache/spider/spider/1.0.0/3c571ccbabdc104a8d1f14edff4ce10d09d7724b0c3665fc42bec1ed51c84bf3...
Traceback (most recent call last):
  File "seq2seq/run_seq2seq.py", line 270, in <module>
    main()
  File "seq2seq/run_seq2seq.py", line 148, in main
    tokenizer=tokenizer,
  File "/app/seq2seq/utils/dataset_loader.py", line 89, in load_dataset
    dataset_dict=_spider_dataset_dict(),
  File "/app/seq2seq/utils/dataset_loader.py", line 45, in <lambda>
    path=data_args.dataset_paths["spider"], cache_dir=model_args.cache_dir
  File "/opt/conda/lib/python3.7/site-packages/datasets/load.py", line 1699, in load_dataset
    use_auth_token=use_auth_token,
  File "/opt/conda/lib/python3.7/site-packages/datasets/builder.py", line 596, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "/opt/conda/lib/python3.7/site-packages/datasets/builder.py", line 690, in _download_and_prepare
    ) from None
OSError: Cannot find data file. 
Original error:
[Errno 20] Not a directory: '/transformers_cache/downloads/2328a961663d7b95ae1aa7a8f378034cc12f525cf9ce537792e7b0856332da67/spider/train_spider.json'

Do I need to do any extra processing to get Spider dataset?

**Comment by tscholak** [comment] 2022-02-22 11:05
Hi @PramuPerera,
No additional processing should be required. Perhaps the download failed somehow. Can you just run this again? Also, what platform are you on?

**Comment by kotalaraghava** [comment] 2022-02-26 11:08
Hey @tscholak ,

I am also facing the same issue. Builder is trying to find this file `/transformers_cache/downloads/e802648de711b5135807858200be8df74dc610c8606926d2c47de192c44790e9/cosql_dataset/sql_state_tracking/cosql_train.json` but there is just this `/transformers_cache/downloads/e802648de711b5135807858200be8df74dc610c8606926d2c47de192c44790e9` no files is created inside this.

and I see .lock file is created in the same directory. 

![no_folder](https://user-images.githubusercontent.com/72073231/155840780-464f55a9-5d95-41f9-baf3-f17de713bef0.PNG)

And I tried deleting python lock files to see if it helps to download but no luck.

I am using aws-ec2(Deep Learning Base AMI (Ubuntu 16.04) Version 21.0)  machine as a host if it helps.

kindly provide if any solution comes to your mind, otherwise tomorrow I am gonna debug little bit details to nail down the issue.


Thanks,
Raghav

**Comment by elena-soare** [comment] 2022-02-27 11:17
Hello! I am actually getting the same issue at the moment, even if before it worked just fine.
BR, 
Elena

**Comment by elena-soare** [comment] 2022-02-27 11:17
Hello! I am actually getting the same issue at the moment, even if before it worked just fine.
BR, 
Elena

**Comment by PramuPerera** [comment] 2022-02-27 14:45
A temporary work around is to manually download spider.zip from the google drive and change the _URL in spider/spider.py.

**Comment by tscholak** [comment] 2022-03-02 18:58
I was able to reproduce the issue, but I have not yet had the time to investigate the cause of the error.

**Comment by tscholak** [comment] 2022-03-04 20:35
The issue was upstream and has been recently fixed, https://github.com/huggingface/datasets/issues/3786

**Comment by tscholak** [comment] 2022-03-04 20:35
I will update the image to include that fix.

**Comment by tscholak** [comment] 2022-03-04 23:00
I have merged a fix. It should work again.
I recommend removing the download cache, so that the zip file is downloaded again.
The issue was caused by a bug in huggingface's `datasets` library that caused the code to download the no-virus-check page instead of the zip file from the google drive.

**Comment by Marchanjo** [comment] 2022-03-09 12:35
Hi everyone, 

I faced the same problem, it occurs due to the Google Drive virus check message. 
Reference:
[Fix: Bypass Virus Checks in Google Drive Links (CNN-DM dataset) #3785](https://github.com/huggingface/datasets/pull/3785)

To fix is simple just include  `&confirm=t` at the URL end.

File: picard/seq2seq/datasets/spider/spider.py
Near to Line 45
From:
`_URL = "https://drive.google.com/uc?export=download&id=1_AckYkinAnhqmRQtGsQgUKAnTHxxX5J0`

To
`_URL = "https://drive.google.com/uc?export=download&id=1_AckYkinAnhqmRQtGsQgUKAnTHxxX5J0&confirm=t" `

**Comment by tscholak** [comment] 2022-03-09 14:45
Hi @Marchanjo,
Thanks for sharing! With the fixes I pushed recently, the change you're proposing shouldn't be necessary anymore. Did you still run into problems with the latest image?

**Comment by Marchanjo** [comment] 2022-03-09 16:15
Hi @tscholak, thank you! 
I did not test the latest image yet.

**Comment by tscholak** [comment] 2022-03-16 18:29
This issue has been fixed. If it still doesn't work for you, please pull the latest docker image(s) and delete the `datasets` cache in your `$HF_HOME` where huggingface saves its temporary files.

**Closed by tscholak** 2022-03-16 18:29 UTC
Labels: bug
