### ISSUE TITLE
DuplicatedKeysError(key) when loading cosql dataset

### ISSUE THREAD

**Issue by Soistesimmer** [ElementAI/picard#11] opened 2021-10-20 12:19 UTC
Hi, great work!
I ran into DuplicatedKeysError(key) when loading cosql dataset. It seems that there exist different training examples with the same 'key'. I fix the _generate_examples function of [cosql.py] (https://github.com/ElementAI/picard/blob/main/seq2seq/datasets/cosql/cosql.py) like this and it works:
```python
    def _generate_examples(self, data_filepath, db_path):
        """This function returns the examples in the raw (text) form."""
        logger.info("generating examples from = %s", data_filepath)
        key = 0 # indexing each training instance
        with open(data_filepath, encoding="utf-8") as f:
            cosql = json.load(f)
            for idx, sample in enumerate(cosql):
                db_id = sample["database_id"]
                if db_id not in self.schema_cache:
                    self.schema_cache[db_id] = dump_db_json_schema(
                        db_path + "/" + db_id + "/" + db_id + ".sqlite", db_id
                    )
                schema = self.schema_cache[db_id]

                db_stuff = {
                    "db_id": db_id,
                    "db_path": db_path,
                    "db_table_names": schema["table_names_original"],
                    "db_column_names": [
                        {"table_id": table_id, "column_name": column_name}
                        for table_id, column_name in schema["column_names_original"]
                    ],
                    "db_column_types": schema["column_types"],
                    "db_primary_keys": [{"column_id": column_id} for column_id in schema["primary_keys"]],
                    "db_foreign_keys": [
                        {"column_id": column_id, "other_column_id": other_column_id}
                        for column_id, other_column_id in schema["foreign_keys"]
                    ],
                }

                yield key, {
                    "utterances": [sample["final"]["utterance"]],
                    "query": sample["final"]["query"],
                    "turn_idx": -1,
                    **db_stuff,
                }
                key += 1
                utterances = []
                for turn_idx, turn in enumerate(sample["interaction"]):
                    utterances.extend((utterance.strip() for utterance in turn["utterance"].split(sep="|")))
                    yield key, {
                        "utterances": list(utterances),
                        "query": turn["query"],
                        "turn_idx": turn_idx,
                        **db_stuff,
                    }
                    key += 1
```
Besides, have you ever tried other hyperparameters to speed up training, such as smaller batch size? Any advice will be appreciated!

**Comment by tscholak** [comment] 2021-10-20 21:04
Hi @Soistesimmer!
Thank you very much for reporting this bug. I've pushed a fix based on your suggestion, https://github.com/ElementAI/picard/commit/25496df6641e1341ad0912b712a8be38da14ac03.
I hope the issue is resolved for you.
Torsten

**Closed** 2021-10-21 03:39 UTC
